baseURL = "https://superhub.io"
languageCode = "en-us"
title = "SuperHub"
disableKinds = ["taxonomy", "taxonomyTerm"]

[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

[params]
agilestacks_overview = "docs/AgileStacks_Datasheet_Mar21.pdf"
agilestacks_docs_url = "https://github.com/agilestacks/google-stacks/blob/main/hub-anthos-with-demo-app.md"
agilestacks_url      = "https://www.agilestacks.com"
wiki_url             = "https://github.com/agilestacks/hub/wiki"
git_repo_url         = "https://github.com/agilestacks/hub"
slack_support_url    = "https://agilestacks-support.slack.com"
hub_version          = "v1.0.2"

title = "SuperHub® Automation Hub"
brief = "Hub CLI is stack packaging and deployment tool."
description = "Hub CLI implements push button deployments from customizable GitOps templates.  Trust the complete automation hub delivering composable stacks with speed, security, and reliability. "
