baseURL = "https://superhub.io"
languageCode = "en-us"
title = "SuperHub"
disableKinds = ["taxonomy", "taxonomyTerm"]

[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

[params]
agilestacks_docs_url = "https://docs.agilestacks.com"
agilestacks_url      = "https://www.agilestacks.com"
github_repo_url      = "agilestacks/hub"
slack_support_url    = "https://agilestacks-support.slack.com"
hub_windows_bin_url  = "https://controlplane.agilestacks.io/dist/hub-cli/hub.windows_amd64.exe"

title = "SuperHub® Automation Hub"
brief = "Hub CLI is stack packaging and deployment tool."
description = "Hub CLI implements push button deployments from customizable GitOps templates.  Trust the complete automation hub delivering composable stacks with speed, security, and reliability. "