baseURL = "https://superhub.io"
languageCode = "en-us"
title = "SuperHub"
disableKinds = ["taxonomy", "taxonomyTerm"]

[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

[params]
wiki_url     = "https://github.com/agilestacks/hub/wiki"
git_repo_url = "https://github.com/agilestacks/hub"

hub_version = "v1.0.4"

sandboxes_git_repo_url = "https://github.com/agilestacks/google-stacks"

sandbox_gke_anthos_demo_app = "hub-anthos-with-demo-app.md"
sandbox_gke_demo_app = "hub-gke-with-demo-app.md"
sandbox_gke = "hub-just-gke.md"
sandbox_php_web_server = "hub-php-web-server.md"
sandbox_cloud_sql = "hub-cloud-sql-perftest.md"
sandbox_cloud_composer = "hub-composer-demo-app.md"

gcp_cloudshell_url = "https://ssh.cloud.google.com/cloudshell/editor?cloudshell_image=gcr.io/superhub/cloud-shell"

title = "SuperHub® Automation Hub"
brief = "Hub CLI is stack packaging and deployment tool."
description = "Hub CLI implements push button deployments from customizable GitOps templates.  Trust the complete Automation Hub delivering composable stacks with speed, security, and reliability. "
