baseURL: https://superhub.io
languageCode: en-us
title: SuperHub
disableKinds:
  - taxonomy
  - taxonomyTerm

sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5

params:
  title: SuperHub® Automation Hub
  brief: Hub CLI is stack packaging and deployment tool.
  description: "Hub CLI implements push button deployments from customizable GitOps templates. Trust the complete Automation Hub delivering composable stacks with speed, security, and reliability."

  hub_version: v1.0.5

  headerButtons:
    - title: GitHub
      url: https://github.com/agilestacks/hub
      icon: "fab fa-github-square"
    - title: Wiki
      url: https://github.com/agilestacks/hub/wiki
      icon: "fas fa-book"
    - title: GCP Sandboxes
      url: https://gcp.devops.delivery
      icon: "fas fa-layer-group"
