baseURL: https://superhub.io
languageCode: en-us
title: Hubctl
disableKinds:
  - taxonomy
  - taxonomyTerm

sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5

params:
  title: Hubctl
  brief: Hubctl is stack packaging and deployment tool.
  description: "Hubctl implements push button deployments from customizable GitOps templates. Trust the complete Automation Hub delivering composable stacks with speed, security, and reliability."

  headerButtons:
    - title: GitHub
      url: https://github.com/epam/hubctl
      icon: "fab fa-github-square"
    - title: Wiki
      url: https://github.com/epam/hubctl/wiki
      icon: "fas fa-book"
    - title: GCP Sandboxes
      url: https://gcp.devops.delivery
      icon: "fas fa-layer-group"
